{
"alumCodigo": 1,
"curso":"I"
"alumNombre": "Roberto Antonio",
"alumclases": [ {"claseCodigo":1,"claseDescrip":"espanol", "claseNota":[10,56,12,80]},
                {"claseCodigo":2,"claseDescrip":"matematicas", "claseNota":[100,34,23,65]},
                {"claseCodigo":3,"claseDescrip":"Ciencias", "claseNota":[78,67,34,78]},
                {"claseCodigo":4,"claseDescrip":"Etica", "claseNota":[67,34,45,68]},
                {"claseCodigo":5,"claseDescrip":"Quimica", "claseNota":[56,89,45,36]},
                {"claseCodigo":6,"claseDescrip":"E. Fisica", "claseNota":[67,78,56,73]},
                {"claseCodigo":7,"claseDescrip":"Fisica E.", "claseNota":[78,78,67,45]},
                {"claseCodigo":8,"claseDescrip":"Sociologia", "claseNota":[67,67,78,56]},
                {"claseCodigo":9,"claseDescrip":"Psicologia", "claseNota":[56,56,67,67]},
                {"claseCodigo":10,"claseDescrip":"Taller", "claseNota":[45,45,56,78]}],
"alumDireccion":"",
"alumFechNacimiento":"12/12/12",
"alumSangTipo": ["a+", "b+","ab+"],
"alumCorreo":"alum1@local.com",
"password" : "alum1",
},
{
"alumCodigo": 2,
"alumNombre": "Marcos Antonio",
"alumclases": [ {"claseCodigo":1,"claseDescrip":"espanol", "claseNota":[10,56,12,80]},
                {"claseCodigo":2,"claseDescrip":"matematicas", "claseNota":[100,34,23,65]},
                {"claseCodigo":3,"claseDescrip":"espanol", "claseNota":[78,67,34,78]},
                {"claseCodigo":4,"claseDescrip":"espanol", "claseNota":[67,34,45,68]},
                {"claseCodigo":5,"claseDescrip":"espanol", "claseNota":[56,89,45,36]},
                {"claseCodigo":6,"claseDescrip":"espanol", "claseNota":[67,78,56,73]},
                {"claseCodigo":7,"claseDescrip":"espanol", "claseNota":[78,78,67,45]},
                {"claseCodigo":8,"claseDescrip":"espanol", "claseNota":[67,67,78,56]},
                {"claseCodigo":9,"claseDescrip":"espanol", "claseNota":[56,56,67,67]},
                {"claseCodigo":10,"claseDescrip":"espanol", "claseNota":[45,45,56,78]}],
"alumDireccion":"",
"alumFechNacimiento":"12/12/12",
"alumSangTipo": ["a+", "b+","ab+"],
"alumCorreo":"alum2@local.com",
"password" : "alum2",
},
{
"alumCodigo": 3,
"alumNombre": "Angel Antonio",
"alumclases": [ {"claseCodigo":1,"claseDescrip":"espanol", "claseNota":[10,56,12,80]},
                {"claseCodigo":2,"claseDescrip":"matematicas", "claseNota":[100,34,23,65]},
                {"claseCodigo":3,"claseDescrip":"espanol", "claseNota":[78,67,34,78]},
                {"claseCodigo":4,"claseDescrip":"espanol", "claseNota":[67,34,45,68]},
                {"claseCodigo":5,"claseDescrip":"espanol", "claseNota":[56,89,45,36]},
                {"claseCodigo":6,"claseDescrip":"espanol", "claseNota":[67,78,56,73]},
                {"claseCodigo":7,"claseDescrip":"espanol", "claseNota":[78,78,67,45]},
                {"claseCodigo":8,"claseDescrip":"espanol", "claseNota":[67,67,78,56]},
                {"claseCodigo":9,"claseDescrip":"espanol", "claseNota":[56,56,67,67]},
                {"claseCodigo":10,"claseDescrip":"espanol", "claseNota":[45,45,56,78]}],
"alumDireccion":"",
"alumFechNacimiento":"12/12/12",
"alumSangTipo": ["a+", "b+","ab+"],
"alumCorreo":"alum3@local.com",
"password" : "alum3",
},
{
"alumCodigo": 4,
"alumNombre": "Daniel Antonio",
"alumclases": [ {"claseCodigo":1,"claseDescrip":"espanol", "claseNota":[10,56,12,80]},
                {"claseCodigo":2,"claseDescrip":"matematicas", "claseNota":[100,34,23,65]},
                {"claseCodigo":3,"claseDescrip":"espanol", "claseNota":[78,67,34,78]},
                {"claseCodigo":4,"claseDescrip":"espanol", "claseNota":[67,34,45,68]},
                {"claseCodigo":5,"claseDescrip":"espanol", "claseNota":[56,89,45,36]},
                {"claseCodigo":6,"claseDescrip":"espanol", "claseNota":[67,78,56,73]},
                {"claseCodigo":7,"claseDescrip":"espanol", "claseNota":[78,78,67,45]},
                {"claseCodigo":8,"claseDescrip":"espanol", "claseNota":[67,67,78,56]},
                {"claseCodigo":9,"claseDescrip":"espanol", "claseNota":[56,56,67,67]},
                {"claseCodigo":10,"claseDescrip":"espanol", "claseNota":[45,45,56,78]}],
"alumDireccion":"",
"alumFechNacimiento":"12/12/12",
"alumSangTipo": ["a+", "b+","ab+"]
"alumDonaciones":[  {"descrip":"comeder", "cantidad":100},
                    {"descrip":"comeder", "cantidad":100},
                    {"descrip":"comeder", "cantidad":100}],
"alumCorreo":"alum@elObelicos.com",
"password" : "admin",
"alumMensajes": [{"remitente":"", "fecha":"","data":""},
                {"remitente":"", "fecha":"","data":""},
                {"remitente":"", "fecha":"","data":""}],
"alumSangTipo": ["a+", "b+","ab+"],
"alumCorreo":"alum4@local.com",
"password" : "alum4",
},
{
"alumCodigo": 5,
"alumNombre": "Carlos Antonio",
"alumclases": [ {"claseCodigo":1,"claseDescrip":"espanol", "claseNota":[10,56,12,80]},
                {"claseCodigo":2,"claseDescrip":"matematicas", "claseNota":[100,34,23,65]},
                {"claseCodigo":3,"claseDescrip":"espanol", "claseNota":[78,67,34,78]},
                {"claseCodigo":4,"claseDescrip":"espanol", "claseNota":[67,34,45,68]},
                {"claseCodigo":5,"claseDescrip":"espanol", "claseNota":[56,89,45,36]},
                {"claseCodigo":6,"claseDescrip":"espanol", "claseNota":[67,78,56,73]},
                {"claseCodigo":7,"claseDescrip":"espanol", "claseNota":[78,78,67,45]},
                {"claseCodigo":8,"claseDescrip":"espanol", "claseNota":[67,67,78,56]},
                {"claseCodigo":9,"claseDescrip":"espanol", "claseNota":[56,56,67,67]},
                {"claseCodigo":10,"claseDescrip":"espanol", "claseNota":[45,45,56,78]}],
"alumDireccion":"",
"alumFechNacimiento":"12/12/12",
"alumSangTipo": ["a+", "b+","ab+"],
"alumCorreo":"alum5@local.com",
"password" : "alum5",
},
{
"alumCodigo": 6,
"alumNombre": "Rigo Antonio",
"alumclases": [ {"claseCodigo":1,"claseDescrip":"espanol", "claseNota":[10,56,12,80]},
                {"claseCodigo":2,"claseDescrip":"matematicas", "claseNota":[100,34,23,65]},
                {"claseCodigo":3,"claseDescrip":"espanol", "claseNota":[78,67,34,78]},
                {"claseCodigo":4,"claseDescrip":"espanol", "claseNota":[67,34,45,68]},
                {"claseCodigo":5,"claseDescrip":"espanol", "claseNota":[56,89,45,36]},
                {"claseCodigo":6,"claseDescrip":"espanol", "claseNota":[67,78,56,73]},
                {"claseCodigo":7,"claseDescrip":"espanol", "claseNota":[78,78,67,45]},
                {"claseCodigo":8,"claseDescrip":"espanol", "claseNota":[67,67,78,56]},
                {"claseCodigo":9,"claseDescrip":"espanol", "claseNota":[56,56,67,67]},
                {"claseCodigo":10,"claseDescrip":"espanol", "claseNota":[45,45,56,78]}],
"alumDireccion":"",
"alumFechNacimiento":"12/12/12",
"alumSangTipo": ["a+", "b+","ab+"],
"alumCorreo":"alum6@local.com",
"password" : "alum6",
}

{ "curso":"II",
  "horario":[{"Lunes":["Matematicas", "Espanol","Sociologia","Psicologia"]},
      {"Martes":["Matematicas", "Espanol","Sociologia","Psicologia"]},
      {"Miercoles":["Matematicas", "Espanol","Sociologia","Psicologia"]},
      {"Jueves":["Matematicas", "Espanol","Sociologia","Psicologia"]},
      {"Viernes":["Matematicas", "Espanol","Sociologia","Psicologia"]}]
}
  "II":[{"Lunes":["Matematicas", "Espanol","Sociologia","Psicologia"]},
          {"Martes":["Matematicas", "Espanol","Sociologia","Psicologia"]},
          {"Miercoles":["Matematicas", "Espanol","Sociologia","Psicologia"]},
          {"Jueves":["Matematicas", "Espanol","Sociologia","Psicologia"]},
          {"Viernes":["Matematicas", "Espanol","Sociologia","Psicologia"]}],
  "III":[{"Lunes":["Matematicas", "Espanol","Sociologia","Psicologia"]},
              {"Martes":["Matematicas", "Espanol","Sociologia","Psicologia"]},
              {"Miercoles":["Matematicas", "Espanol","Sociologia","Psicologia"]},
              {"Jueves":["Matematicas", "Espanol","Sociologia","Psicologia"]},
              {"Viernes":["Matematicas", "Espanol","Sociologia","Psicologia"]}],
}

{
    "codigo":"",
    "evento":"",
    "lugar":"",
    "fecha":""
}

// db: marcial
// coleccion: alumnos //
